version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password  # Change 'password' to a strong password
    networks:
      - app-network

  python-app:
    build: .
    container_name: python-app
    depends_on:
      - mongodb
      - neo4j
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge