version: '3.7'

services:
  mongodb:
    image: mongo-with-tools
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

  python-app:
    build: .
    depends_on:
      mongodb:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    volumes:
      - .:/app
    command: ["python", "app.py"]
  
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p password 'RETURN 1' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  neo4j_data: