version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

  python-app:
    build: .
    container_name: python-app
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge