   version: '3.7'

   services:
     mongodb:
       image: mongo-with-tools
       ports:
         - "27017:27017"
       healthcheck:
         test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
         interval: 30s
         timeout: 10s
         retries: 5